<?xml version="1.0" encoding="utf-8"?><Database Name="BDDUIOHELPDESK01" Class="DCMailDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.TBL_MAILCONFIG" Member="TBL_MAILCONFIG">
    <Type Name="TBL_MAILCONFIG">
      <Column Name="mai_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="mai_servidor" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="mai_puerto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="mai_user" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="mai_password" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="mai_ssl" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="mai_status" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="mai_add" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_MAIL" Member="TBL_MAIL">
    <Type Name="TBL_MAIL">
      <Column Name="mus_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="mus_fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="mus_correo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="mus_sendstatus" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="mus_errorstatus" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="mus_messageerror" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="mus_status" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="mus_add" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="mus_nombre" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>