//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.HELPDESK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MAILCONFIG
    {
        public int mai_id { get; set; }
        public string mai_servidor { get; set; }
        public int mai_puerto { get; set; }
        public string mai_user { get; set; }
        public string mai_password { get; set; }
        public bool mai_ssl { get; set; }
        public string mai_status { get; set; }
        public System.DateTime mai_add { get; set; }
    }
}
