//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.HELPDESK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MAIL
    {
        public int mus_id { get; set; }
        public System.DateTime mus_fecha { get; set; }
        public string mus_correo { get; set; }
        public bool mus_sendstatus { get; set; }
        public bool mus_errorstatus { get; set; }
        public string mus_messageerror { get; set; }
        public string mus_status { get; set; }
        public System.DateTime mus_add { get; set; }
        public string mus_nombre { get; set; }
    }
}
